In [1]:
import pandas as pd

df = pd.read_csv('data/PS_20174392719_1491204439457_log.csv')

df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [2]:
print(df.shape)
df['isFraud'].value_counts()
df['isFraud'].value_counts(normalize=True) * 100

(6362620, 11)

isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

In [3]:
df.groupby('type')['isFraud'].sum()

type
CASH_IN        0
CASH_OUT    4116
DEBIT          0
PAYMENT        0
TRANSFER    4097
Name: isFraud, dtype: int64

In [4]:
fraud_summary = df.groupby('type')['isFraud'].agg(['sum', 'count'])
fraud_summary['fraud_rate_%'] = (fraud_summary['sum'] / fraud_summary['count']) * 100
fraud_summary

           sum    count  fraud_rate_%
type
CASH_IN      0  1399284      0.000000
CASH_OUT  4116  2237500      0.183955
DEBIT        0    41432      0.000000
PAYMENT      0  2151495      0.000000
TRANSFER  4097   532909      0.768799

In [5]:
total_fraud = df['isFraud'].sum()
caught_by_rule = df[df['isFraud'] == 1]['isFlaggedFraud'].sum()

print(f"Total actual fraud cases: {total_fraud}")
print(f"Caught by naive rule: {caught_by_rule}")
print(f"Rule catches: {(caught_by_rule/total_fraud)*100:.2f}% of all fraud")

Total actual fraud cases: 8213
Caught by naive rule: 16
Rule catches: 0.19% of all fraud

In [6]:
fraud_df = df[df['isFraud'] == 1]
drained = (fraud_df['newbalanceOrig'] == 0).sum()
total_fraud = len(fraud_df)

print(f"Fraud cases where sender's balance hit exactly 0: {drained} out of {total_fraud}")
print(f"That's {(drained/total_fraud)*100:.2f}% of all fraud")

Fraud cases where sender's balance hit exactly 0: 8053 out of 8213
That's 98.05% of all fraud